name: kekasir
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  dropdown_search: ^6.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  logger: ^2.5.0
  lottie: ^3.3.1
  mat_month_picker_dialog: ^1.1.2
  shared_preferences: ^2.5.2
  tutorial_coach_mark: ^1.2.13
  url_launcher: ^6.3.1
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon-app.png" # Ganti dengan lokasi ikonmu
  adaptive_icon_foreground: "assets/images/icon-app.png" # Untuk Android adaptive icon
  adaptive_icon_background: "assets/images/icon-app.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/animations/
    - assets/sections/
    
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend-SemiBold.ttf
        - asset: assets/fonts/Lexend-Bold.ttf