name: kekasir
description: "Solusi kasir modern yang bisa diajakin main cepat"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  dropdown_search: ^6.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  logger: ^2.5.0
  lottie: ^3.3.1
  mat_month_picker_dialog: ^1.1.2
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  internet_connection_checker: ^3.0.1
  flutter_inappwebview: ^6.0.0
  auto_size_text: ^3.0.0
  blue_thermal_printer: ^1.2.3
  simple_barcode_scanner: ^0.3.0
  in_app_update: ^4.2.3
  cached_network_image: ^3.4.1
  image: ^4.5.4
  showcaseview: ^4.0.1
  animated_text_kit: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon-app-v2.png" # Ganti dengan lokasi ikonmu

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/animations/
    - assets/sections/
    
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend-SemiBold.ttf
        - asset: assets/fonts/Lexend-Bold.ttf